my_twi/kombinaciay/urls.py
from django.urls import path, include
from kombinaciay import views

app_name = 'kombinaciay'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('student_list/', views.StudentList.as_view(), name='students_list'),
    path('student_detail/<int:pk>', views.StudentDetail.as_view(), name='student_detail'),
    path('student_create/', views.StudentCreate.as_view(), name='student_create'),
    path('student_update/<int:pk>', views.StudentUpdate.as_view(), name='student_update'),
    path('student_del/<int:pk>', views.StudentDelete.as_view(), name='student_del'),
]

my_twi/my_twi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kombinaciay.urls', namespace='kombinaciay'))
]

my_twi/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']),]

    def __str__(self):
        return self.title

my_twi/kombinaciay/models.py
import uuid

from django.db import models

# Create your models here.
GENDER_CHOICE = (
    ('M', 'man'),
    ('F', 'woman')
)

class University(models.Model):
    name = models.CharField('Название', max_length=255)
    def __str__(self):
        return self.name

class Lesson(models.Model):
    name = models.CharField('Название', max_length=255)

class Student(models.Model):
    first_name = models.CharField('Имя', max_length=255)
    second_name = models.CharField('Фамилия', max_length=255)
    gender = models.CharField('Пол', max_length=255, choices=GENDER_CHOICE,
                              default=GENDER_CHOICE[0])
    lesson_count = models.IntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    date_birth = models.DateField(blank=True, null=True)
    dc = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    dm = models.DateTimeField(auto_now=True, blank=True, null=True)
    university = models.ForeignKey(University,
                                   on_delete=models.CASCADE,
                                   related_name='student',
                                   null=True,
                                   blank=True)
    lesson = models.ManyToManyField(Lesson, blank=True)


class StudentId(models.Model):
    number = models.CharField(max_length=252, unique=True)
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name='studentid')

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'
        ordering = ('number',)
        abstract = True

    def __str__(self):
        return f'{self.number} - {self.student.name}'

my_twi/kombinaciay/forms.py
from django import forms

from kombinaciay import models


class StudentSearch(forms.Form):
    first_name = forms.CharField(label='Поиск по имени', required=False, help_text='Поиск по имени студента')
    lesson_count = forms.IntegerField(label='Количество занятий', min_value= 0, required=False)

    def clean_first_name(self):
        name = self.cleaned_data['first_name']
        if '/' in name:
            raise forms.ValidationError('Имя не должно содержать /')
        return name

    def clean(self):  # тоже самое что и функция выше, но можно сразу несколько условий записать
        count = self.cleaned_data['lesson_count']
        if count == 10:
            raise forms.ValidationError('Число не равно 10')
        return count

class StudentCreate(forms.ModelForm):
    first_name = forms.CharField(label='Имя', required=False)
    lesson_count = forms.IntegerField(label='Количество занятий', min_value=0, required=False)

    def clean_first_name(self):
        name = self.cleaned_data['first_name']
        if name.isdigit():
            raise forms.ValidationError('Имя не должно быть числом !')
        return name


    class Meta:
        model = models.Student
        fields = '__all__'

my_twi/blog/views.py
from django.shortcuts import render

# Create your views here.

my_twi/kombinaciay/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from kombinaciay import models

from kombinaciay import forms

from kombinaciay import filters


class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['title']= self.get_title()
        return context

def index(request):
    user = request.user.username
    html = "<html> <body> <h1> Hello %s</h1> </body> </html>" % user
    return HttpResponse(html)

class StudentList(TitleMixin, ListView):
    model= models.Student
    template_name = 'kombinaciay/student_list'
    context_object_name = 'students'
    title = 'Список студентов'

    def get_filters(self):
        return filters.StudentFilter(self.request.GET)
    def get_queryset(self):
        # first_name = self.request.GET.get('first_name')
        # lesson_count = self.request.GET.get('lesson_count')
        # qs = models.Student.objects.all()
        # if first_name:
        #     return qs.filter(Q(first_name__icontains=first_name) | Q(lesson_count=lesson_count))
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['form'] = forms.StudentSearch(self.request.GET or None)
        context['filter'] = self.get_filters()
        context['count'] = self.get_queryset().count()
        return context


class StudentDetail(TitleMixin, DetailView):
    model = models.Student
    template_name = 'kombinaciay/student_detail.html'
    context_object_name = 'student'
    title = 'Студент'


class StudentCreate(TitleMixin, CreateView):
    model = models.Student
    template_name = 'kombinaciay/student_create.html'
    form_class = forms.StudentCreate
    success_url = reverse_lazy('kombinaciay:students_list')

class StudentUpdate(TitleMixin, UpdateView):
    model = models.Student
    template_name = 'kombinaciay/student_create.html'
    fields = ('lesson_count',)
    success_url = reverse_lazy('kombinaciay:students_list')

class StudentDelete(TitleMixin, DeleteView):
    model = models.Student
    template_name = 'kombinaciay/student_del.html'
    success_url = reverse_lazy('kombinaciay:students_list')

my_twi/kombinaciay/templates/kombinaciay/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/admin/">Админка</a></li>
            <li><a class="dropdown-item" href="{ % url 'kombinaciay:students_list %}">Список студентов</a></li>
            <li><a class="dropdown-item" href="{ % url 'kombinaciay:student_create %}">Добавить студента</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>

my_twi/kombinaciay/templates/kombinaciay/student_create.html
{% extends 'kombinaciay/base.html'%}
{% block content %}
<form action="{% url 'kombinaciay:student_create' %}" method="POST">
    {% csrf_token %}
    {{ form.first_name.label_tag }}
    {{ form.first_name }}
    {{ form.first_name.errors }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

my_twi/kombinaciay/templates/kombinaciay/student_del.html
{% extends 'kombinaciay/base.html'%}
{% block content %}
<form action="{% url 'kombinaciay:student_del' pk=student.pk %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Удалить</button>
</form>
{% endblock %}

my_twi/kombinaciay/templates/kombinaciay/student_detail.html
{% extends 'kombinaciay/base.html'%}
{% block content %}
  <body>
    <h1>{{student.first_name}} {{student.second_name}}</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}

my_twi/kombinaciay/templates/kombinaciay/student_list.html
{% extends 'kombinaciay/base.html'%}
{% block content %}
  <body>
    <form method="GET">
    {{ filter.form.as_p }}
    <button type="submit">Поиск</button>
  </form>
  <h2>Список студентов: {{ count }}</h2>
    <h1>Список студентов</h1>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">Обновить</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Количество занятий</th>
      {% if request.user.is_superuser %}
      <th scope="col">Активен</th>
      {% endif %}
       <th scope="col"> Удалить</th>
    </tr>
  </thead>
  <tbody>
  {% for student in students %}
    <tr>
      <td><a href="{% url 'kombinaciay:student_update' pk=student.pk %}">Обновить</a></td>
      <td>{{student.first_name}}</td>
      <td>{{student.second_name}}</td>
      <td>{{student.lesson_count}}</td>
      {% if request.user.is_superuser %}
      <td>{{student.is_active}}</td>
      {% endif %}
      <td><a href="{% url 'kombinaciay:student_del' pk=student.pk %}">Удалить</a></td>
    </tr>
  {% empty %}
  <tr>
    <td>Список пустой</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}